1

diff --git a/lib/libbash b/lib/libbash
--- a/lib/libbash
+++ b/lib/libbash
@@ -23,7 +23,7 @@
 #     ####### and load library ########
 # # check has package
 # function    machine_has() {
-#         hash "$1" > /dev/null 2>&1
+#         hash "${1}" > /dev/null 2>&1
 #         return $?; }
 # # Check and set download tool
 # echo "Check and set download tool..."
@@ -222,17 +222,17 @@ function    machine_has()
     {
         eval $invocation
 
-        hash "$1" > /dev/null 2>&1
+        hash "${1}" > /dev/null 2>&1
         return $?
     }
 # check has value
 function    has_value()
     {
-        [[ -n $1 ]] && return $TRUE || return $FALSE
+        [[ -n ${1} ]] && return $TRUE || return $FALSE
     }
 function    has_empty()
     {
-        [[ -z $1 ]] && return $TRUE || return $FALSE
+        [[ -z ${1} ]] && return $TRUE || return $FALSE
     }
 
 
@@ -243,18 +243,18 @@ function    has_empty()
 # download_with_curl /winrar.zip http://media.matmagoc.com/winrar.zip
 function    download_with_curl()
     {
-        FILE_TEMP="$1"
+        FILE_TEMP="${1}"
         [[ -f $FILE_TEMP ]] && rm -f $FILE_TEMP
             say "Downloading ..."
-            curl -Ls "$2" -o "$FILE_TEMP"
+            curl -Ls "${2}" -o "$FILE_TEMP"
     }
 # download_with_wget /winrar.zip http://media.matmagoc.com/winrar.zip
 function    download_with_wget()
     {
-        FILE_TEMP="$1"
+        FILE_TEMP="${1}"
         [[ -f $FILE_TEMP ]] && rm -f $FILE_TEMP
             say "Downloading ..."
-            wget -O $FILE_TEMP --no-check-certificate "$2"
+            wget -O $FILE_TEMP --no-check-certificate "${2}"
     }
 function    download_option()
     {
@@ -280,7 +280,7 @@ function    download_option()
     ####### Change path #######
     ###########################
 
-# input - $1
+# input - ${1}
 function    to_lowercase()
     {
         #eval $invocation
@@ -304,7 +304,7 @@ function    trim()
     }
 
 # args:
-# input - $1
+# input - ${1}
 function    remove_trailing_slash()
     {
         #eval $invocation
@@ -315,7 +315,7 @@ function    remove_trailing_slash()
     }
 
 # args:
-# input - $1
+# input - ${1}
 function    remove_beginning_slash()
     {
         #eval $invocation
@@ -326,8 +326,8 @@ function    remove_beginning_slash()
     }
 
 # args:
-# root_path - $1
-# child_path - $2 - this parameter can be empty
+# root_path - ${1}
+# child_path - ${2} - this parameter can be empty
 function    combine_paths()
     {
         eval $invocation
@@ -338,7 +338,7 @@ function    combine_paths()
             return $FALSE
         fi
 
-        local root_path="$(remove_trailing_slash "$1")"
+        local root_path="$(remove_trailing_slash "${1}")"
         local child_path="$(remove_beginning_slash "${2:-}")"
         say "combine_paths: root_path=$root_path"
         say "combine_paths: child_path=$child_path"
@@ -353,7 +353,7 @@ function    combine_paths()
 ####### Run from URL #######
 function    run_url()
     {
-        bash <(curl -s $1)
+        bash <(curl -s ${1})
     }
 
 
@@ -502,8 +502,8 @@ function    get_machine_architecture()
 ####### add a user #######
 function    add_a_user()
     {
-        USER=$1
-        PASSWORD=$2
+        USER=${1}
+        PASSWORD=${2}
         shift; shift;
         # Having shifted twice, the rest is now comments ...
         COMMENTS=$@
@@ -540,14 +540,14 @@ function    require_root()
     }
 ##################################################################
 # Purpose: Return true $user exits in /etc/passwd
-# Arguments: $1 (username) -> Username to check in /etc/passwd
+# Arguments: ${1} (username) -> Username to check in /etc/passwd
 # Return: True or False
 # Find out if user account vivek exits or not
 # is_user "vivek" && echo "Account found." || echo "Account not found."
 ##################################################################
 function    is_user() 
     {
-        local u="$1"
+        local u="${1}"
         grep -q "^${u}" $PASSWD_FILE    && return $TRUE                     || return $FALSE
     }
 function    is_user_say() 
@@ -579,8 +579,8 @@ function    now()
 ## @return Time elapsed between the 'start' and 'stop' parameters.
 function    elapsed()
     {
-        START="$1"
-        STOP="$2"
+        START="${1}"
+        STOP="${2}"
 
         ELAPSED=$(( STOP - START ))
         echo "Your elapsed time ${ELAPSED} seconds"
@@ -618,7 +618,7 @@ function    stop_watch()
 ####### Generate password #######
 function    gen_passwd () 
     { 
-        local l=$1;
+        local l=${1};
         [[ "$l" == "" ]] && l=16;
         tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${l} | xargs
     }
@@ -634,8 +634,8 @@ function    copy_files_or_dirs_from_list()
     {
         eval $invocation
 
-        local root_path="$(remove_trailing_slash "$1")"
-        local out_path="$(remove_trailing_slash "$2")"
+        local root_path="$(remove_trailing_slash "${1}")"
+        local out_path="$(remove_trailing_slash "${2}")"
         local override="$3"
         local override_switch=$(if [[ "$override" = false ]]; then printf -- "-n"; fi)
         
@@ -674,25 +674,25 @@ function    dircopy()
             return $FALSE
         fi
 
-        if [[ ! -d "$1" ]]; then
-            echo "$1 is not a directory." 1>&2
+        if [[ ! -d "${1}" ]]; then
+            echo "${1} is not a directory." 1>&2
             return $FALSE
         fi
 
-        if [[ -f "$2" ]]; then
-            echo "$2 is not a directory." 1>&2
+        if [[ -f "${2}" ]]; then
+            echo "${2} is not a directory." 1>&2
             return $FALSE
         fi
 
-        if [[ ! -d "$2" ]]; then
-            mkdir -p "$2"
+        if [[ ! -d "${2}" ]]; then
+            mkdir -p "${2}"
         fi
 
-        cd "$2"
+        cd "${2}"
         TARGET=`pwd`
         cd $CURDIR
 
-        cd "$1"
+        cd "${1}"
         find . -depth -print          |
             cpio -pdmu $TARGET 2>&1  |
             grep -iv "blocks"
@@ -701,16 +701,16 @@ function    dircopy()
 # Defning return code check function
 function    die()
     {
-        if [[ $1 -ne 0 ]]; then
-            echo "Error: $2"
-            exit $1
+        if [[ ${1} -ne 0 ]]; then
+            echo "Error: ${2}"
+            exit ${1}
         fi
     } >&2 # function writes to stderr
 
 # calculator
 function    calc()
     {
-        ((cipher=$1))
+        ((cipher=${1}))
         echo $cipher
         return $TRUE
     }
@@ -723,7 +723,7 @@ function    read_line()
             # reading each line
             echo "Line $n : $line"
             n=$((n+1))
-        done < $1
+        done < ${1}
         return $TRUE
     }
 
@@ -759,8 +759,8 @@ function    count_line()
 #loading
 function    loading()
     {
-        for a in `seq 1 $1`; do
-            echo "Loading: $a/$1" 
+        for a in `seq 1 ${1}`; do
+            echo "Loading: $a/${1}" 
             sleep 1;
         done
 
@@ -771,10 +771,10 @@ function    loading()
 # check Greater Lesser
 function    check_greater()
     {
-        if [[ $1 -gt $2 ]]; then
-            echo "$1 > $2"
-        elif [[ $1 -lt $2 ]]; then
-            echo "$1 < $2"
+        if [[ ${1} -gt ${2} ]]; then
+            echo "${1} > ${2}"
+        elif [[ ${1} -lt ${2} ]]; then
+            echo "${1} < ${2}"
         fi
         return $TRUE
     }
@@ -789,20 +789,20 @@ function    print_date()
 ####### Check file and folder #######
 function    check_file_block()
     {
-        [[ -b $1 ]] && return $TRUE || return $FALSE
+        [[ -b ${1} ]] && return $TRUE || return $FALSE
 
     }
 function    check_file_special_character()
     {
-        [[ -c $1 ]] && return $TRUE || return $FALSE
+        [[ -c ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_folder()
     {
-        [[ -d $1 ]] && return $TRUE || return $FALSE
+        [[ -d ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_filefolder()
     {
-        [[ -e $1 ]] && return $TRUE || return $FALSE
+        [[ -e ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_filefolder_say()
     {
@@ -813,51 +813,51 @@ function    check_filefolder_say()
     }
 function    check_file()
     {
-        [[ -f $1 ]] && return $TRUE || return $FALSE
+        [[ -f ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_owned_groupid()
     {
-        [[ -G $1 ]] && return $TRUE || return $FALSE
+        [[ -G ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_groupid()
     {
-        [[ -g $1 ]] && return $TRUE || return $FALSE
+        [[ -g ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_sticky()
     {
-        [[ -k $1 ]] && return $TRUE || return $FALSE
+        [[ -k ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_symlink()
     {
-        [[ -L $1 ]] && return $TRUE || return $FALSE
+        [[ -L ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_owned_userid()
     {
-        [[ -O $1 ]] && return $TRUE || return $FALSE
+        [[ -O ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_read()
     {
-        [[ -r $1 ]] && return $TRUE || return $FALSE
+        [[ -r ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_socket()
     {
-        [[ -S $1 ]] && return $TRUE || return $FALSE
+        [[ -S ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_nonzero()
     {
-        [[ -s $1 ]] && return $TRUE || return $FALSE
+        [[ -s ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_userid()
     {
-        [[ -u $1 ]] && return $TRUE || return $FALSE
+        [[ -u ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_write()
     {
-        [[ -w $1 ]] && return $TRUE || return $FALSE
+        [[ -w ${1} ]] && return $TRUE || return $FALSE
     }
 function    check_file_run()
     {
-        [[ -x $1 ]] && return $TRUE || return $FALSE
+        [[ -x ${1} ]] && return $TRUE || return $FALSE
     }
 
 # core command create object
@@ -868,7 +868,7 @@ function    core_command_create_object()
         else
             say "Creating ${object_create}.."
             ${command_create_object} "${object_create}"
-            # ${command_check_object} ${object_create}      && say "${object_create} created" || say_err "Cant create ${object_create}" ; return $FALSE
+            ${command_check_object} ${object_create}      && say "${object_create} created" || say_err "Cant create ${object_create}" ; return $FALSE
         fi
         return $TRUE
     }
@@ -1011,13 +1011,13 @@ alias delele_filesfolders=remove_filesfolders
 # set filefolder owner
 function    set_filefolder_owner()
     {
-        check_filefolder $2                 && chown -R $1 $2 || say_err "Cant set owner"; return $FALSE
+        check_filefolder ${2}                 && chown -R ${1} ${2} || say_err "Cant set owner"; return $FALSE
         return $TRUE
     }
 # set filefolder mod
 function    set_filefolder_mod()
     {
-        check_filefolder $2                 && chmod -R $1 $2 || say_err "Cant set mod"; return $FALSE
+        check_filefolder ${2}                 && chmod -R ${1} ${2} || say_err "Cant set mod"; return $FALSE
         return $TRUE
     }
 
@@ -1069,7 +1069,7 @@ function    dircmp()
         #
         while :
         do
-            case $1 in
+            case ${1} in
                 -v)  VERBOSE=TRUE
                     shift
                     ;;
@@ -1089,10 +1089,10 @@ function    dircmp()
         #
         if [[ $# -eq 1 ]]; then
             DIR1="."
-            DIR2="$1"
+            DIR2="${1}"
         elif [[ $# -eq 2 ]]; then
-            DIR1="$1"
-            DIR2="$2"
+            DIR1="${1}"
+            DIR2="${2}"
         else
             echo "$USAGE" 1>&2
             return $FALSE
@@ -1224,7 +1224,7 @@ function    findfile()
             return $FALSE
         fi
 
-        NAME=$1
+        NAME=${1}
         shift
 
         find "${@:-.}" -name "$NAME" -print
@@ -1248,8 +1248,8 @@ alias search_folder=findfile
 ## content with the new one.
 function    str_replace() 
     {
-        local ORIG="$1"
-        local DEST="$2"
+        local ORIG="${1}"
+        local DEST="${2}"
         local DATA="$3"
 
         echo "${DATA//$ORIG/$DEST}"
@@ -1267,8 +1267,8 @@ function    str_replace_in_file()
     {
         [[ $# -lt 3 ]] && return $FALSE
 
-        local ORIG="$1"
-        local DEST="$2"
+        local ORIG="${1}"
+        local DEST="${2}"
 
         for FILE in "${@:3:$#}"; do
             check_file "$FILE" || return $FALSE
@@ -1343,7 +1343,7 @@ function    findstr()
             USAGE="Usage: $CMDNAME [-i][-v] string [filename]"
             while :
             do
-                case $1 in
+                case ${1} in
                     -i)  I=-i      # Ignore case
                             shift
                             ;;
@@ -1370,7 +1370,7 @@ function    findstr()
             return $FALSE
         fi
 
-        STRING=$1
+        STRING=${1}
         FILENAME=${2:-"*"}
 
         find . \( -type f -o -type l \) -name "$FILENAME" -print |
@@ -1402,22 +1402,22 @@ function    is_newer()
             return $FALSE
         fi
 
-        if [ ! -e $1 -o ! -e $2 ]; then
+        if [ ! -e ${1} -o ! -e ${2} ]; then
             return $FALSE       # No
         fi
 
-        if [[ -n "`find $1 -newer $2 -print`" ]]; then
-            say "File/Folder $1 newer $2"
+        if [[ -n "`find ${1} -newer ${2} -print`" ]]; then
+            say "File/Folder ${1} newer ${2}"
             return $TRUE       # Yes
         else
-            say "File/Folder $2 newer $1"
+            say "File/Folder ${2} newer ${1}"
             return $FALSE      # No
         fi
     }
 
 function    hex2decimal()
     {
-        NUM=`echo $1    | tr '[a-f]' '[A-F]'`
+        NUM=`echo ${1}    | tr '[a-f]' '[A-F]'`
         echo 16i $NUM p | dc
     }
 
@@ -1437,24 +1437,24 @@ function    is_numeric()
         #    will return false (1).
         #    
         if [[ $# -ne 1 ]]; then
-            say_warning "This $1 is not numeric"
+            say_warning "This ${1} is not numeric"
             return $FALSE
         fi
 
-        expr "$1" + 1 >/dev/null 2>&1
+        expr "${1}" + 1 >/dev/null 2>&1
         if [[ $? -ge 2 ]]; then
-            say_warning "This $1 is not numeric"
+            say_warning "This ${1} is not numeric"
             return $FALSE
         fi
 
-        say "This $1 is numeric"
+        say "This ${1} is numeric"
         return $TRUE
     }
 
 # check process
 function    check_process()
     {
-        grep -x $1 >/dev/null               && return $TRUE         || return $FALSE
+        grep -x ${1} >/dev/null               && return $TRUE         || return $FALSE
     }
 function    check_process_say()
     {
@@ -1756,7 +1756,7 @@ function    is_ipv4()
     {
         local -r regex='^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
 
-        [[ $1 =~ $regex ]]
+        [[ ${1} =~ $regex ]]
         return $?
     }
 
@@ -1768,7 +1768,7 @@ function    is_ipv4()
 ## @retval 1 in others cases.
 function    is_fqdn()
     {
-        echo "$1" | grep -Pq '(?=^.{4,255}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}\.?$)'
+        echo "${1}" | grep -Pq '(?=^.{4,255}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}\.?$)'
 
         return $?
     }
@@ -1781,9 +1781,9 @@ function    is_fqdn()
 ## @retval 1 in others cases.
 function    is_ipv4_netmask()
     {
-        is_ipv4 "$1" || return $FALSE
+        is_ipv4 "${1}" || return $FALSE
 
-        IFS='.' read -r ipb[1] ipb[2] ipb[3] ipb[4] <<< "$1"
+        IFS='.' read -r ipb[1] ipb[2] ipb[3] ipb[4] <<< "${1}"
 
         local -r list_msb='0 128 192 224 240 248 252 254'
 
@@ -1814,8 +1814,8 @@ function    is_ipv4_cidr()
     {
         local -r regex='^[[:digit:]]{1,2}$'
 
-        [[ $1 =~ $regex ]]      || return $FALSE
-        [[ "$1" -gt 32 ]]         || [[ "$1" -lt 0 ]] && return $FALSE
+        [[ ${1} =~ $regex ]]      || return $FALSE
+        [[ "${1}" -gt 32 ]]         || [[ "${1}" -lt 0 ]] && return $FALSE
 
         return $TRUE
     }
@@ -1828,7 +1828,7 @@ function    is_ipv4_cidr()
 ## @retval 1 in others cases.
 function    is_ipv4_subnet()
     {
-        IFS='/' read -r tip tmask <<< "$1"
+        IFS='/' read -r tip tmask <<< "${1}"
 
         is_ipv4_cidr "$tmask"   || return $FALSE
         is_ipv4 "$tip"          || return $FALSE
@@ -1846,11 +1846,11 @@ function    is_ipv4_subnet()
 ## @return Network address.
 function    get_ipv4_network()
     {
-        is_ipv4 "$1"            || return $FALSE
-        is_ipv4_netmask "$2"    || return $FALSE
+        is_ipv4 "${1}"            || return $FALSE
+        is_ipv4_netmask "${2}"    || return $FALSE
 
-        IFS='.' read -r ipb1 ipb2 ipb3 ipb4 <<< "$1"
-        IFS='.' read -r mb1 mb2 mb3 mb4 <<< "$2"
+        IFS='.' read -r ipb1 ipb2 ipb3 ipb4 <<< "${1}"
+        IFS='.' read -r mb1 mb2 mb3 mb4 <<< "${2}"
 
         echo "$((ipb1 & mb1)).$((ipb2 & mb2)).$((ipb3 & mb3)).$((ipb4 & mb4))"
     }
@@ -1865,11 +1865,11 @@ function    get_ipv4_network()
 ## @return Broadcast address.
 function    get_ipv4_broadcast()
     {
-        is_ipv4 "$1"            || return $FALSE
-        is_ipv4_netmask "$2"    || return $FALSE
+        is_ipv4 "${1}"            || return $FALSE
+        is_ipv4_netmask "${2}"    || return $FALSE
 
-        IFS='.' read -r ipb1 ipb2 ipb3 ipb4 <<< "$1"
-        IFS='.' read -r mb1 mb2 mb3 mb4 <<< "$2"
+        IFS='.' read -r ipb1 ipb2 ipb3 ipb4 <<< "${1}"
+        IFS='.' read -r mb1 mb2 mb3 mb4 <<< "${2}"
 
         nmb1=$((mb1 ^ 255))
         nmb2=$((mb2 ^ 255))
@@ -1888,12 +1888,12 @@ function    get_ipv4_broadcast()
 ## @return CIDR notation of the given decimal netmask.
 function    mask2cidr()
     {
-        is_ipv4_netmask "$1"    || return $FALSE
+        is_ipv4_netmask "${1}"    || return $FALSE
 
         local x=${1##*255.}
         set -- 0^^^128^192^224^240^248^252^254^ $(( (${#1} - ${#x})*2 )) "${x%%.*}"
         x=${1%%$3*}
-        echo $(( $2 + (${#x}/4) ))
+        echo $(( ${2} + (${#x}/4) ))
     }
 
 ## @fn cidr2mask()
@@ -1905,11 +1905,11 @@ function    mask2cidr()
 ## @return Decimal notation of the given CIDR.
 function    cidr2mask()
     {
-        is_ipv4_cidr "$1"       || return $FALSE
+        is_ipv4_cidr "${1}"       || return $FALSE
 
         local i mask=""
-        local full_octets=$(($1/8))
-        local partial_octet=$(($1%8))
+        local full_octets=$((${1}/8))
+        local partial_octet=$((${1}%8))
 
         for ((i=0;i<4;i+=1)); do
             if [[ $i -lt $full_octets ]]; then
