1

diff --git a/lib/libbash b/lib/libbash
--- a/lib/libbash
+++ b/lib/libbash
@@ -70,7 +70,17 @@ function export_all()
                     check_file_groupid check_file_sticky check_file_symlink check_file_owned_userid check_file_read \
                     check_file_socket check_file_nonzero check_file_userid check_file_write check_file_run create_folder \
                     create_file remove_folder remove_file remove_filefolder set_filefolder_owner set_filefolder_mod \
-                    dircmp findfile  str_replace_in_file findstr is_newer hex2decimal is_numeric check_process check_process_say
+                    dircmp findfile  str_replace_in_file findstr is_newer hex2decimal is_numeric check_process check_process_say \
+                    check_files_block check_files_block_say check_files_special_character check_files_special_character_say \
+                    check_folders check_folders_say check_filefolders check_filefolders_say check_files check_files_say \
+                    check_files_owned_groupid check_files_owned_groupid_say check_files_groupid check_files_groupid_say \
+                    check_files_sticky check_files_sticky_say check_files_symlink check_files_symlink_say check_files_owned_userid \
+                    check_files_owned_userid_say check_files_read check_files_read_say check_files_socket check_files_socket_say \
+                    check_files_nonzero check_files_nonzero_say check_files_userid check_files_userid_say check_files_write \
+                    check_files_write_say check_files_run check_files_run_say create_folders create_files remove_folders \
+                    remove_files remove_filefolders set_file_owner set_folder_owner set_filefolder_owner set_file_mod \
+                    set_folder_mod set_filefolder_mod core_command_create_object core_command_install core_command_create_object \
+                    core_command_remove_object core_command_set_object 
     # Function Install
         export -f check_epel check_epel_say install_epel remove_epel install_gosu install_package install_package_run \
                     install_curl install_wget install_java_jre
@@ -200,13 +210,13 @@ function    e_note()
 ####### Echo Warning #######
 function    say_warning()
     {
-        printf "%b\n" "${yellow:-} ➜Warning: $@${normal:-}"
+        printf "%b\n" "${yellow:-} ➜ Warning: $@${normal:-}"
     }
 
 ####### Echo Error #######
 function    say_err()
     {
-        printf "%b\n" "${red:-} ✖Error: $@${normal:-}" >&2
+        printf "%b\n" "${red:-} ✖ Error: $@${normal:-}" >&2
     }
 
 ####### Echo Normal #######
@@ -1230,7 +1240,7 @@ alias delele_filesfolders=remove_filesfolders
 function    core_command_set_object()
     {
         $command_check_object ${object_set}                 && $command_set_object ${object_mode} ${object_set} || return $FALSE
-        return $TRUE
+        say "set mode to ${object_set} "                    && return $TRUE
     }
 
 # set file owner
@@ -1906,8 +1916,9 @@ function    install_java_jre()
                     return $FALSE
                 fi
             core_command_install
-            check_folder /usr/lib/jvm/java-1.${OPENJDKV}-openjdk/jre && return $TRUE || return $FALSE
+            check_folder /usr/lib/jvm/java-1.${OPENJDKV}-openjdk/jre && say "Install ${software} completed!" || return $FALSE
         fi
+        return $TRUE
     }
 
 
